### PR TITLE
Update the Demo branch

### PR DESCRIPTION
**Pull request by thomwiggers**
Turns out, it's a long way behind the other branches. Merge the Thalia folder into demo.

### CODE REVIEW

**Comment by wouterl** [comment]
Any particular reason to change the demo keys?

**Comment by thomwiggers** [comment]
There were no demo keys: the whole folder was missing. 

On 30 November 2015 22:26:27 CET, Wouter Lueks <notifications@github.com> wrote:
>Any particular reason to change the demo keys?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/credentials/irma_configuration/pull/17#issuecomment-160766717

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wouterl** [comment]
I'm not sure that is correct, the keys were there in the demo branch, see 96f40a5b416937bb8d321c3db6eb19287e03795d

**Comment by thomwiggers** [comment]
Hmm, something funky was going on with our fork then…

I'll pop off that commit when I get back on a computer tomorrow. 

On 30 November 2015 22:32:18 CET, Wouter Lueks <notifications@github.com> wrote:
>I'm not sure that is correct, the keys were there in the demo branch,
>see 96f40a5b416937bb8d321c3db6eb19287e03795d
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/credentials/irma_configuration/pull/17#issuecomment-160768086

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by thomwiggers** [comment]
The offending commit has been removed from the branch.

**Pull request merged**
